package utils;

// A接口呼叫记录
public class CBSSAPCC {
	public static final int START_TIME=0;			// 开始时间
	public static final int CDR_ID=1;				// CDR标识号
	public static final int OPC=2;					// OPC
	public static final int DPC=3;					// DPC
	public static final int S_IP=4;					// 源IP
	public static final int D_IP=5;					// 目的IP
	public static final int A_TYPE=6;				// 子业务类型
	public static final int CALL_TYPE=7;			// 呼叫类型
	public static final int CALLING=8;				// 主叫号码
	public static final int CALLING_TYPE=9;			// 主叫号码类型
	public static final int CALLING_PLAN=10;		// 主叫号码编号计划
	public static final int CALLED=11;				// 被叫号码
	public static final int CALLED_TYPE=12;			// 被叫号码类型
	public static final int CALLED_PLAN=13;			// 被叫号码编号计划
	public static final int OTHER_NUM=14;			// 其他号码
	public static final int OTHER_NUM_PROP=15;		// 其他号码类别
	public static final int IMSI=16;				// IMSI
	public static final int ESN=17;					// ESN
	public static final int MS_CLASS=18;			// MS级别
	public static final int SOUR_LAC=19;			// 源LAC
	public static final int SOUR_CI=20;				// 源CI
	public static final int START_LAC=21;			// 业务发起的LAC
	public static final int START_CI=22;			// 业务发起的CI
	public static final int END_LAC=23;				// 业务终止的LAC
	public static final int END_CI=24;				// 业务终止的CI
	public static final int DEST_LAC=25;			// 目标LAC
	public static final int DEST_CI=26;				// 目标CI
	public static final int PR_FLAG=27;				// 寻呼标志
	public static final int CIC5=28;				// 时隙号
	public static final int CIC7=29;				// 系统号
	public static final int A_PROC=30;				// 业务进程
	public static final int A_RESULT=31;			// 业务详细结果
	public static final int DROP_TYPE=32;			// 掉话类型
	public static final int HO_NUM=33;				// BSC内部切换次数
	public static final int HO_CAUSE=34;			// 切换原因
	public static final int HO_RESULT=35;			// 切换业务结果
	public static final int HO_REJECT=36;			// 切换拒绝原因
	public static final int HOFAILURE_CAUSE=37;		// 切换失败原因
	public static final int ASSG_RESULT=38;			// 指配结果
	public static final int ASSG_CAUSE=39;			// 指配失败原因
	public static final int CLEAR_CAUSE=40;			// 清除原因
	public static final int A_CLOSE_REG=41;			// 用户关机
	public static final int USRPR_TIME=42;			// 用户寻呼响应时延
	public static final int NETPR_TIME=43;			// 网络寻呼响应时延
	public static final int RESP_TIME=44;			// 网络响应时延
	public static final int ASSGREQ_TIME=45;		// 指配请求时延
	public static final int ASSGCPL_TIME=46;		// 指配结束时延
	public static final int ALERT_TIME=47;			// 振铃时延
	public static final int CONN_TIME=48;			// 应答时延
	public static final int CLEAR_TIME=49;			// 清除时延
	public static final int RLC_TIME=50;			// 释放时延
	public static final int FL_NUM=51;				// 闪动信息个数
	public static final int SM_NUM=52;				// 短信个数
	public static final int DTMF_NUM=53;			// DTMF消息个数
	public static final int BEAR_PROTO=54;			// 承载类型
	public static final int FRONTNO=55;				// 前端机
	public static final int REMOTENO=56;			// 远程站
	public static final int OFFSET=57;				// 偏移量
	public static final int TALK_TIME =58;			// 通话时长
	public static final int SEIZE_TIME=59;			// 占用时长
	public static final int IN_OUT=60;				// 切入/切出标识
	public static final int MSC_ID=61;				// MSC
	public static final int MGW_ID=62;				// MGW
	public static final int BSC_ID=63;				// BSC
	public static final int O_OPER_ID=64;			// 起源运营商
	public static final int D_OPER_ID=65;			// 目的运营商
	public static final int O_PROV_ID=66;			// 源省
	public static final int O_CITY_ID=67;			// 源城市
	public static final int D_PROV_ID=68;			// 目的省
	public static final int D_CITY_ID=69;			// 目的城市
	public static final int TALK_TIME_ERR=70;		// 通话时长异常标识
	public static final int JOINER_ID =71;			// 关联ID
}
